### ISSUE TITLE
Add translation

### ISSUE THREAD

**Issue by tocalvo** [bq/bitbloq-offline#1]
Include the translation libs from Bitbloq, the grunt tasks and create a poeditor account

**Comment by MechuLopez** [comment]
Hola,
Ya esta disponible la versión offline de BQ? Ahora estamos usando el visualino en la escuela, por problemas que tenemos en la conexión de internet, pero si pudieramos usar la versión bitbloq2 offline seria genial.

**Comment by tocalvo** [comment]
Buenas, 

estamos con ello pero todavía no está del todo terminada :( , tenemos algún error importante en la versión de linux y mac, y algún problema menor de interfaz (como que el componente "encoder" no compila por ejemplo).

Sin embargo en windows 7 o superior está bastante estable y podrías probar si te funciona para tus clases. Pero recuerda probar antes de dar la clase que funciona correctamente y cualquier error puedes notificarlo desde aquí, desde la web bitbloq.bq.com o enviando un email a soporte.bitbloq@bq.com indicando que es en la versión offline.

Para obtenerla puedes clonarte el proyecto y generar una versión desde la rama de desarrollo, o si lo prefieres dime tu email y te mandamos la versión actual para windows ya preparada.

Si estás registrado en Bitbloq online y has marcado la opción de "soy profesor" o "quiero recibir noticias", en cuanto tengamos la versión estable enviaremos un email y podrás usarla o actualizarte.

**Comment by MechuLopez** [comment]
Hola, muchas gracias x la respuesta.
Mi e-mail es merlpzbrv@gmail.com
En los pc's tenemos windows 7 (nos queda un xp q en breve esperamos cambiar para ponerlo al dia).
