### ISSUE TITLE
No se ven fuentes en selector de archivos

### ISSUE THREAD

**Issue by jesuslalvaro** [bq/bitbloq-offline#11]
Xubuntu 64 bits
No se ven fuentes al abrir selector de archivos 
Problema visto en otras aplicaciones basadas en electron
Parece tener que ver con stack ejecutable (execstack flag)
ver issue: https://github.com/electron/electron/issues/11628

Gracias

**Comment by avalero** [comment]
Hola. Bitbloq offline es una versión discontinuada, por lo que ya no recibe soporte.
